- hosts: localhost
  connection: local

  tasks:
    - name: Create Magic3 config directory
      file:
        path: /var/magic3
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Build container
      shell: |
        docker build -t magic3:latest ./containers &&
        docker run -d --name magic3 -p 80:80 \
          -e MYSQL_DATABASE=magic3db \
          -e MYSQL_USER=magic3_user \
          -e MYSQL_PASSWORD=magic3_password \
          --restart=always -v /var/magic3:/var/www/html magic3:latest
